Traceback (most recent call last):
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 216, in get
        extensions = yield self.manager.list_extensions()
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 216, in get
        extensions = yield self.manager.list_extensions()
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 86, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 86, in list_extensions
        pkg_info = yield self._get_pkg_info(name, data)
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 154, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 154, in _get_pkg_info
        outdated = yield self._get_outdated()
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 189, in _load_outdated
        logger=self.log,
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/hellosaumil/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/Users/hellosaumil/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/Users/hellosaumil/anaconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 456, in get_latest_compatible_package_versions
        return handler.latest_compatible_package_versions(names)
      File "/Users/hellosaumil/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 1543, in latest_compatible_package_versions
        raise ValueError(msg % keys)
    ValueError: "['@jupyterlab/github@1.0.1', '@jupyterlab/git@0.8.0', '@jupyterlab/google-drive@1.0.0']" is not a valid npm package